service: ai-chatbot-lambda

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1 # o tu región preferida
  ecr:
    images:
      appimage:
        path: ./

functions:
  api:
    image:
      name: appimage
    events:
      - http:
          path: /meeting/{meetingId}/chat
          method: GET
          cors: true
      - http:
          path: /meeting/{meetingId}/chat
          method: POST
          cors: true

plugins:
  - serverless-offline # para pruebas locales
